name: web_deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setgo
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      
      - run: go version

      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1
        
        
      - name: Install
        run: GOOS=js GOARCH=wasm go build -o web/public/main.wasm ./web/
        
      - run: cp $(go env GOROOT)/misc/wasm/wasm_exec.js web/public
      - run: ls web/public/index.html

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: web/public # The folder the action should deploy.
